version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  versioning-strategy: increase-if-necessary
https://apps.apple.com/us/app/contributions-for-github/id1153432612
